name: Resonance
channels:
- conda-forge
dependencies:
- python=3.11
- mamba
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas >=0.9.1
- ipyleaflet
- ipympl>=0.8.2
- ipywidgets>=8,<9
- jupyterlab>=4.0.5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta>=3,<4
- jupyterlab-geojson>=3,<4
- jupyterlab-night
- plotly>=5,<6
