name: Resonance
channels:
- conda-forge
dependencies:
- python
- bqplot
- ipycanvas 
- ipyleaflet
- ipympl
- ipywidgets
- jupyterlab>
- jupyterlab-fasta
- jupyterlab-geojson
- jupyterlab-night
- plotly
