name: Resonance
channels:
- conda-forge
dependencies:
- python
- npm
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas 
- ipyleaflet
- ipympl
- ipywidgets
- jupyterlab>
- jupyterlab-fasta
- jupyterlab-geojson
- jupyterlab-night
- plotly
